// The gaps this port still carries against the reference managed shell.
//
// Generated from a failing run of the replay in `session_parity_tests.rs` and
// kept honest by three tests there: a difference no entry names fails the
// suite, an entry whose difference no longer reproduces fails it too, and
// every reason stated below has to be a row of a divergence table in
// `docs/parity.md`. Every entry belongs to row 6 of that document, which is the
// row this ledger lowers.
//
// Entries are at field granularity, which is what NFR "no ledger entry is
// scoped wider than one field on one case" asks for: `/modelText` is one
// field, `/sessions/0/manifest/shell` is one field, and `/typedResult` alone
// would be thirteen.

const WHY_RENDERED: &str = "the rendered text is the typed document read back one field per \
    line, so it carries whatever field that document still diverges on for this case (FR-05)";
const WHY_MESSAGE: &str = "the sentence the reference publishes for this action is \
    reference-authored text no committed artifact may carry, so the corpus holds a digest of it \
    and this port answers its own wording";
const WHY_STDIO: &str = "the reference dropped `stdout` and `stderr` from the managed command \
    result in 2.24.2, leaving the interleaved PTY text in `output` alone \
    (vibe/core/tools/builtins/experimental_bash.py:1274-1294 at \
    4a96003, the 2.25.7 pin), and this port still emits both fields beside \
    `output`, so its typed document carries two fields the reference no longer has";
const WHY_MAX_CHARS: &str = "the reference validates `max_bytes` through an alias that also \
    accepts `max_chars` and this port reads only `max_bytes`, so the alias does not bound the \
    window here";
const WHY_SIGNAL_EXIT: &str = "the reference reports a signalled process the way Python's \
    `Popen.returncode` reports it, as the negated signal number, and this port reports -1 for \
    every death by signal";
const WHY_SHELL: &str = "the reference resolves its shell from the environment and accepts a \
    `shell` configuration key, which is how the capture pinned /bin/bash; this port has no such \
    key and starts /bin/sh, so the difference is recorded rather than closed";
const WHY_ERROR_KIND: &str = "the reference refuses these arguments inside the handler and raises \
    its tool error, and this port refuses them at the schema boundary, so both refuse and the \
    kind differs";
const WHY_EMPTY_ARGUMENT: &str = "the reference refuses an empty argument where this port accepts \
    it and answers, so the outcome kind differs on a case neither implementation runs a command \
    for";
const WHY_KILLED_SESSION: &str = "the reference keeps answering for a session it killed and this \
    port stops knowing it, so an inspection after a kill returns there and refuses here";

/// Where `docs/parity.md` holds each reason above, so a gap the replay
/// tolerates is a row a reader can look up rather than a sentence in a test.
/// [`every_recorded_reason_has_exactly_one_divergence_row`] resolves both
/// directions: a reason naming a row nobody wrote fails, and a row the ledger
/// no longer reaches fails too.
const RECORDS: &[Recorded] = &[
    Recorded {
        why: WHY_SHELL,
        row: "The managed shell starts `/bin/sh` and resolves no other",
        table: Table::Open,
    },
    Recorded {
        why: WHY_RENDERED,
        row: "A rendered shell document repeats its typed document's divergence",
        table: Table::Open,
    },
    Recorded {
        why: WHY_STDIO,
        row: "A managed command result still carries `stdout` and `stderr`",
        table: Table::Open,
    },
    Recorded {
        why: WHY_MAX_CHARS,
        row: "The `max_chars` argument alias is unread",
        table: Table::Open,
    },
    Recorded {
        why: WHY_SIGNAL_EXIT,
        row: "A managed session killed by a signal reports -1",
        table: Table::Open,
    },
    Recorded {
        why: WHY_EMPTY_ARGUMENT,
        row: "An empty shell argument is answered rather than refused",
        table: Table::Open,
    },
    Recorded {
        why: WHY_KILLED_SESSION,
        row: "A killed managed session is forgotten",
        table: Table::Open,
    },
    Recorded {
        why: WHY_ERROR_KIND,
        row: "A shell argument is refused at the schema boundary",
        table: Table::Accepted,
    },
    Recorded {
        why: WHY_MESSAGE,
        row: "The managed shell's own action sentences",
        table: Table::Accepted,
    },
];

/// Builds one entry. Every gap this ledger holds belongs to [`SHELL_ROW`],
/// which is the row the replay lowers, so the row is not spelled 2 500 times.
const fn gap(
    tool: &'static str,
    case: &'static str,
    pointer: &'static str,
    closed_by: &'static str,
    why: &'static str,
) -> Divergence {
    Divergence {
        tool,
        case,
        pointer,
        closed_by,
        row: SHELL_ROW,
        why,
    }
}

const LEDGER: &[Divergence] = &[
    gap("bash", "foreground-exit-zero", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash", "foreground-exit-zero", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-exit-zero", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-exit-zero", "/typedResult/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-exit-zero", "/typedResult/stderr", RECORDED, WHY_STDIO),
    gap("bash", "foreground-exit-zero", "/typedResult/stdout", RECORDED, WHY_STDIO),
    gap("bash", "foreground-reads-fixture", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash", "foreground-reads-fixture", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-reads-fixture", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-reads-fixture", "/typedResult/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-reads-fixture", "/typedResult/stderr", RECORDED, WHY_STDIO),
    gap("bash", "foreground-reads-fixture", "/typedResult/stdout", RECORDED, WHY_STDIO),
    gap("bash", "foreground-no-output", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash", "foreground-no-output", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-no-output", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-no-output", "/typedResult/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-no-output", "/typedResult/stderr", RECORDED, WHY_STDIO),
    gap("bash", "foreground-no-output", "/typedResult/stdout", RECORDED, WHY_STDIO),
    gap("bash", "foreground-stderr-only", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash", "foreground-stderr-only", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-stderr-only", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-stderr-only", "/typedResult/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-stderr-only", "/typedResult/stderr", RECORDED, WHY_STDIO),
    gap("bash", "foreground-stderr-only", "/typedResult/stdout", RECORDED, WHY_STDIO),
    gap("bash", "foreground-multiline-output", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash", "foreground-multiline-output", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-multiline-output", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-multiline-output", "/typedResult/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-multiline-output", "/typedResult/stderr", RECORDED, WHY_STDIO),
    gap("bash", "foreground-multiline-output", "/typedResult/stdout", RECORDED, WHY_STDIO),
    gap("bash", "foreground-multibyte-output", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash", "foreground-multibyte-output", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-multibyte-output", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-multibyte-output", "/typedResult/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-multibyte-output", "/typedResult/stderr", RECORDED, WHY_STDIO),
    gap("bash", "foreground-multibyte-output", "/typedResult/stdout", RECORDED, WHY_STDIO),
    gap("bash", "foreground-output-exceeds-window", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash", "foreground-output-exceeds-window", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-output-exceeds-window", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-output-exceeds-window", "/typedResult/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-output-exceeds-window", "/typedResult/stderr", RECORDED, WHY_STDIO),
    gap("bash", "foreground-output-exceeds-window", "/typedResult/stdout", RECORDED, WHY_STDIO),
    gap("bash", "foreground-exit-non-zero", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-exit-non-zero", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-cwd-override", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash", "foreground-cwd-override", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-cwd-override", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-cwd-override", "/typedResult/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-cwd-override", "/typedResult/stderr", RECORDED, WHY_STDIO),
    gap("bash", "foreground-cwd-override", "/typedResult/stdout", RECORDED, WHY_STDIO),
    gap("bash", "foreground-env-override", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash", "foreground-env-override", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-env-override", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-env-override", "/typedResult/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-env-override", "/typedResult/stderr", RECORDED, WHY_STDIO),
    gap("bash", "foreground-env-override", "/typedResult/stdout", RECORDED, WHY_STDIO),
    gap("bash", "foreground-shell-override", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash", "foreground-shell-override", "/typedResult/stderr", RECORDED, WHY_STDIO),
    gap("bash", "foreground-shell-override", "/typedResult/stdout", RECORDED, WHY_STDIO),
    gap("bash", "foreground-empty-command", "/error/type", RECORDED, WHY_ERROR_KIND),
    gap("bash", "foreground-legacy-timeout-field", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash", "foreground-legacy-timeout-field", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-legacy-timeout-field", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-legacy-timeout-field", "/typedResult/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-legacy-timeout-field", "/typedResult/stderr", RECORDED, WHY_STDIO),
    gap("bash", "foreground-legacy-timeout-field", "/typedResult/stdout", RECORDED, WHY_STDIO),
    gap("bash", "foreground-timeout-clamped-to-maximum", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash", "foreground-timeout-clamped-to-maximum", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-timeout-clamped-to-maximum", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-timeout-clamped-to-maximum", "/typedResult/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-timeout-clamped-to-maximum", "/typedResult/stderr", RECORDED, WHY_STDIO),
    gap("bash", "foreground-timeout-clamped-to-maximum", "/typedResult/stdout", RECORDED, WHY_STDIO),
    gap("bash", "background-returns-immediately", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash", "background-returns-immediately", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "background-returns-immediately", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "background-returns-immediately", "/typedResult/shell", RECORDED, WHY_SHELL),
    gap("bash", "background-returns-immediately", "/typedResult/stderr", RECORDED, WHY_STDIO),
    gap("bash", "background-returns-immediately", "/typedResult/stdout", RECORDED, WHY_STDIO),
    gap("bash", "soft-timeout-backgrounds-the-session", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash", "soft-timeout-backgrounds-the-session", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "soft-timeout-backgrounds-the-session", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "soft-timeout-backgrounds-the-session", "/typedResult/shell", RECORDED, WHY_SHELL),
    gap("bash", "soft-timeout-backgrounds-the-session", "/typedResult/stderr", RECORDED, WHY_STDIO),
    gap("bash", "soft-timeout-backgrounds-the-session", "/typedResult/stdout", RECORDED, WHY_STDIO),
    gap("bash", "hard-timeout-kills-the-session", "/sessions/0/manifest/exit_code", RECORDED, WHY_SIGNAL_EXIT),
    gap("bash", "hard-timeout-kills-the-session", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "hard-timeout-kills-the-session", "/sessions/0/sessionInfo/exit_code", RECORDED, WHY_SIGNAL_EXIT),
    gap("bash", "hard-timeout-kills-the-session", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "background-poll-source", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash", "background-poll-source", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "background-poll-source", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "background-poll-source", "/typedResult/shell", RECORDED, WHY_SHELL),
    gap("bash", "background-poll-source", "/typedResult/stderr", RECORDED, WHY_STDIO),
    gap("bash", "background-poll-source", "/typedResult/stdout", RECORDED, WHY_STDIO),
    gap("bash_output", "poll-before-any-output", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_output", "poll-before-any-output", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_output", "poll-before-any-output-with-max-bytes", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_output", "poll-before-any-output-with-max-bytes", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_output", "poll-negative-cursor", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_output", "poll-negative-cursor", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_output", "poll-zero-max-bytes", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_output", "poll-zero-max-bytes", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_output", "poll-waits-for-the-session-to-exit", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_output", "poll-waits-for-the-session-to-exit", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_output", "poll-after-completion", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_output", "poll-after-completion", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_output", "poll-from-a-cursor", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_output", "poll-from-a-cursor", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_output", "poll-from-a-cursor-past-the-end", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_output", "poll-from-a-cursor-past-the-end", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_output", "poll-with-max-bytes", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_output", "poll-with-max-bytes", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_output", "poll-with-the-max-chars-alias", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash_output", "poll-with-the-max-chars-alias", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_output", "poll-with-the-max-chars-alias", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_output", "poll-with-the-max-chars-alias", "/typedResult/next_cursor", RECORDED, WHY_MAX_CHARS),
    gap("bash_output", "poll-with-the-max-chars-alias", "/typedResult/output", RECORDED, WHY_MAX_CHARS),
    gap("bash_output", "poll-with-the-max-chars-alias", "/typedResult/truncated", RECORDED, WHY_MAX_CHARS),
    gap("bash_output", "poll-wait-clamped-to-the-maximum", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_output", "poll-wait-clamped-to-the-maximum", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "background-input-target", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash", "background-input-target", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "background-input-target", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "background-input-target", "/typedResult/shell", RECORDED, WHY_SHELL),
    gap("bash", "background-input-target", "/typedResult/stderr", RECORDED, WHY_STDIO),
    gap("bash", "background-input-target", "/typedResult/stdout", RECORDED, WHY_STDIO),
    gap("bash_stdin", "write-text-to-a-running-session", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_stdin", "write-text-to-a-running-session", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_stdin", "write-multibyte-text", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_stdin", "write-multibyte-text", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_stdin", "write-base64-bytes", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_stdin", "write-base64-bytes", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_stdin", "write-a-control-key", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_stdin", "write-a-control-key", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_stdin", "write-two-control-keys", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_stdin", "write-two-control-keys", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_stdin", "write-an-empty-text", "/outcome", RECORDED, WHY_EMPTY_ARGUMENT),
    gap("bash_stdin", "write-nothing", "/error/type", RECORDED, WHY_ERROR_KIND),
    gap("bash_stdin", "write-nothing", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_stdin", "write-nothing", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_stdin", "write-text-and-control-together", "/error/type", RECORDED, WHY_ERROR_KIND),
    gap("bash_stdin", "write-text-and-control-together", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_stdin", "write-text-and-control-together", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_stdin", "write-an-unknown-control-key", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_stdin", "write-an-unknown-control-key", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_stdin", "write-invalid-base64", "/error/type", RECORDED, WHY_ERROR_KIND),
    gap("bash_stdin", "write-invalid-base64", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_stdin", "write-invalid-base64", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-input-target-exits", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash", "foreground-input-target-exits", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-input-target-exits", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-input-target-exits", "/typedResult/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-input-target-exits", "/typedResult/stderr", RECORDED, WHY_STDIO),
    gap("bash", "foreground-input-target-exits", "/typedResult/stdout", RECORDED, WHY_STDIO),
    gap("bash_stdin", "write-to-a-session-that-exited", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_stdin", "write-to-a-session-that-exited", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_sessions", "inspect-without-a-session-id", "/error/type", RECORDED, WHY_ERROR_KIND),
    gap("bash_sessions", "kill-without-a-session-id", "/error/type", RECORDED, WHY_ERROR_KIND),
    gap("bash_sessions", "reset-with-no-session", "/modelText", LICENSING, WHY_RENDERED),
    gap("bash_sessions", "reset-with-no-session", "/typedResult/message", LICENSING, WHY_MESSAGE),
    gap("bash_sessions", "reset-with-clear-logs-and-no-session", "/modelText", LICENSING, WHY_RENDERED),
    gap("bash_sessions", "reset-with-clear-logs-and-no-session", "/typedResult/message", LICENSING, WHY_MESSAGE),
    gap("bash", "background-first-session", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash", "background-first-session", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "background-first-session", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "background-first-session", "/typedResult/shell", RECORDED, WHY_SHELL),
    gap("bash", "background-first-session", "/typedResult/stderr", RECORDED, WHY_STDIO),
    gap("bash", "background-first-session", "/typedResult/stdout", RECORDED, WHY_STDIO),
    gap("bash", "background-second-session", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash", "background-second-session", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "background-second-session", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "background-second-session", "/typedResult/shell", RECORDED, WHY_SHELL),
    gap("bash", "background-second-session", "/typedResult/stderr", RECORDED, WHY_STDIO),
    gap("bash", "background-second-session", "/typedResult/stdout", RECORDED, WHY_STDIO),
    gap("bash_sessions", "list-two-sessions", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash_sessions", "list-two-sessions", "/typedResult/sessions/0/shell", RECORDED, WHY_SHELL),
    gap("bash_sessions", "list-two-sessions", "/typedResult/sessions/1/shell", RECORDED, WHY_SHELL),
    gap("bash_sessions", "inspect-a-running-session", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash_sessions", "inspect-a-running-session", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_sessions", "inspect-a-running-session", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_sessions", "inspect-a-running-session", "/typedResult/session/shell", RECORDED, WHY_SHELL),
    gap("bash_sessions", "inspect-with-max-bytes", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash_sessions", "inspect-with-max-bytes", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_sessions", "inspect-with-max-bytes", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_sessions", "inspect-with-max-bytes", "/typedResult/session/shell", RECORDED, WHY_SHELL),
    gap("bash_sessions", "inspect-with-the-max-chars-alias", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash_sessions", "inspect-with-the-max-chars-alias", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_sessions", "inspect-with-the-max-chars-alias", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_sessions", "inspect-with-the-max-chars-alias", "/typedResult/session/shell", RECORDED, WHY_SHELL),
    gap("bash_sessions", "kill-a-running-session", "/modelText", LICENSING, WHY_RENDERED),
    gap("bash_sessions", "kill-a-running-session", "/sessions/0/manifest/exit_code", RECORDED, WHY_SIGNAL_EXIT),
    gap("bash_sessions", "kill-a-running-session", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_sessions", "kill-a-running-session", "/sessions/0/sessionInfo", RECORDED, WHY_KILLED_SESSION),
    gap("bash_sessions", "kill-a-running-session", "/typedResult/message", LICENSING, WHY_MESSAGE),
    gap("bash_sessions", "kill-a-running-session", "/typedResult/session/shell", RECORDED, WHY_SHELL),
    gap("bash_sessions", "kill-a-running-session", "/typedResult/session/exit_code", RECORDED, WHY_SIGNAL_EXIT),
    gap("bash_sessions", "list-after-a-kill", "/modelText/described", RECORDED, WHY_RENDERED),
    gap("bash_sessions", "list-after-a-kill", "/modelText/length", RECORDED, WHY_RENDERED),
    gap("bash_sessions", "list-after-a-kill", "/typedResult/sessions", RECORDED, WHY_KILLED_SESSION),
    gap("bash_sessions", "inspect-a-killed-session", "/outcome", RECORDED, WHY_KILLED_SESSION),
    gap("bash_sessions", "kill-an-already-killed-session", "/outcome", RECORDED, WHY_KILLED_SESSION),
    gap("bash_sessions", "reset-the-remaining-session", "/modelText", LICENSING, WHY_RENDERED),
    gap("bash_sessions", "reset-the-remaining-session", "/typedResult/message", LICENSING, WHY_MESSAGE),
    gap("bash_sessions", "reset-the-remaining-session", "/typedResult/sessions/0/exit_code", RECORDED, WHY_SIGNAL_EXIT),
    gap("bash_sessions", "reset-the-remaining-session", "/typedResult/sessions/0/shell", RECORDED, WHY_SHELL),
    gap("bash_sessions", "list-after-a-reset", "/modelText/described", RECORDED, WHY_RENDERED),
    gap("bash_sessions", "list-after-a-reset", "/modelText/length", RECORDED, WHY_RENDERED),
    gap("bash_sessions", "list-after-a-reset", "/typedResult/sessions", RECORDED, WHY_KILLED_SESSION),
    gap("bash_sessions", "reset-and-clear-the-logs", "/modelText", LICENSING, WHY_RENDERED),
    gap("bash_sessions", "reset-and-clear-the-logs", "/typedResult/message", LICENSING, WHY_MESSAGE),
    gap("bash", "foreground-log-source", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash", "foreground-log-source", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-log-source", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-log-source", "/typedResult/shell", RECORDED, WHY_SHELL),
    gap("bash", "foreground-log-source", "/typedResult/stderr", RECORDED, WHY_STDIO),
    gap("bash", "foreground-log-source", "/typedResult/stdout", RECORDED, WHY_STDIO),
    gap("bash_log_file", "read-a-session-log-from-the-start", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_log_file", "read-a-session-log-from-the-start", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_log_file", "read-with-max-bytes", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_log_file", "read-with-max-bytes", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_log_file", "read-with-the-max-chars-alias", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash_log_file", "read-with-the-max-chars-alias", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_log_file", "read-with-the-max-chars-alias", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_log_file", "read-with-the-max-chars-alias", "/typedResult/content", RECORDED, WHY_MAX_CHARS),
    gap("bash_log_file", "read-with-the-max-chars-alias", "/typedResult/next_cursor", RECORDED, WHY_MAX_CHARS),
    gap("bash_log_file", "read-with-the-max-chars-alias", "/typedResult/truncated", RECORDED, WHY_MAX_CHARS),
    gap("bash_log_file", "read-from-an-offset", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_log_file", "read-from-an-offset", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_log_file", "read-from-an-offset-past-the-end", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_log_file", "read-from-an-offset-past-the-end", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_log_file", "read-a-log-that-was-deleted", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_log_file", "read-a-log-that-was-deleted", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_log_file", "read-a-negative-offset", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_log_file", "read-a-negative-offset", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_log_file", "read-by-relative-path", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_log_file", "read-by-relative-path", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash_log_file", "read-without-a-session-or-a-path", "/error/type", RECORDED, WHY_ERROR_KIND),
    gap("bash_log_file", "write-without-content", "/outcome", RECORDED, WHY_EMPTY_ARGUMENT),
    gap("bash", "background-live-log-source", "/modelText", RECORDED, WHY_RENDERED),
    gap("bash", "background-live-log-source", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash", "background-live-log-source", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
    gap("bash", "background-live-log-source", "/typedResult/shell", RECORDED, WHY_SHELL),
    gap("bash", "background-live-log-source", "/typedResult/stderr", RECORDED, WHY_STDIO),
    gap("bash", "background-live-log-source", "/typedResult/stdout", RECORDED, WHY_STDIO),
    gap("bash_log_file", "write-to-a-live-session-log", "/sessions/0/manifest/shell", RECORDED, WHY_SHELL),
    gap("bash_log_file", "write-to-a-live-session-log", "/sessions/0/sessionInfo/shell", RECORDED, WHY_SHELL),
];
