// The gaps this port still carries against the reference managed shell.
//
// Generated from a failing run of the replay in `session_parity_tests.rs` and
// kept honest by two tests there: a difference no entry names fails the suite,
// and an entry whose difference no longer reproduces fails it too. Every entry
// belongs to row 6 of `docs/parity.md`, which is the row this ledger lowers.
//
// Entries are at field granularity, which is what NFR "no ledger entry is
// scoped wider than one field on one case" asks for: `/modelText` is one
// field, `/sessions/0/manifest/shell` is one field, and `/typedResult` alone
// would be thirteen.

/// The story that bounds a managed window the way the reference bounds it.
const US_301: &str = "US-301";
/// The story that records what is left in the divergence tables.
const US_306: &str = "US-306";

const WHY_RENDERED: &str = "the rendered text is the typed document read back one field per \
    line, so it carries whatever field that document still diverges on for this case (FR-05)";
const WHY_MESSAGE: &str = "the sentence the reference publishes for this action is \
    reference-authored text no committed artifact may carry, so the corpus holds a digest of it \
    and this port answers its own wording";
const WHY_LINE_ENDINGS: &str = "this port's managed terminal writes CRLF into the session log \
    where the reference's writes LF, so the raw window differs while the normalized `stdout` \
    matches";
const WHY_MAX_CHARS: &str = "the reference validates `max_bytes` through an alias that also \
    accepts `max_chars` and this port reads only `max_bytes`, so the alias does not bound the \
    window here";
const WHY_MANAGED_WINDOW: &str = "this port bounds a managed command window with the inline \
    budget where the reference bounds it with the output budget (FR-11)";
const WHY_SIGNAL_EXIT: &str = "the reference reports a signalled process the way Python's \
    `Popen.returncode` reports it, as the negated signal number, and this port reports -1 for \
    every death by signal";
const WHY_TRUNCATED_READER: &str = "this port names the dropped tail in `reader_error` when a \
    window is truncated and the reference leaves the field null, so the two records disagree on a \
    field neither truncates";
const WHY_SHELL: &str = "the reference resolves its shell from the environment and accepts a \
    `shell` configuration key, which is how the capture pinned /bin/bash; this port has no such \
    key and starts /bin/sh, so the difference is recorded rather than closed";
const WHY_ERROR_KIND: &str = "the reference refuses these arguments inside the handler and raises \
    its tool error, and this port refuses them at the schema boundary, so both refuse and the \
    kind differs";
const WHY_EMPTY_ARGUMENT: &str = "the reference refuses an empty argument where this port accepts \
    it and answers, so the outcome kind differs on a case neither implementation runs a command \
    for";
const WHY_KILLED_SESSION: &str = "the reference keeps answering for a session it killed and this \
    port stops knowing it, so an inspection after a kill returns there and refuses here";

/// Builds one entry. Every gap this ledger holds belongs to [`SHELL_ROW`],
/// which is the row the replay lowers, so the row is not spelled 2 500 times.
const fn gap(
    tool: &'static str,
    case: &'static str,
    pointer: &'static str,
    closed_by: &'static str,
    why: &'static str,
) -> Divergence {
    Divergence {
        tool,
        case,
        pointer,
        closed_by,
        row: SHELL_ROW,
        why,
    }
}

const LEDGER: &[Divergence] = &[
    gap("bash", "foreground-exit-zero", "/modelText", US_306, WHY_RENDERED),
    gap("bash", "foreground-exit-zero", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-exit-zero", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-exit-zero", "/typedResult/output", US_306, WHY_LINE_ENDINGS),
    gap("bash", "foreground-exit-zero", "/typedResult/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-reads-fixture", "/modelText", US_306, WHY_RENDERED),
    gap("bash", "foreground-reads-fixture", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-reads-fixture", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-reads-fixture", "/typedResult/output", US_306, WHY_LINE_ENDINGS),
    gap("bash", "foreground-reads-fixture", "/typedResult/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-no-output", "/modelText", US_306, WHY_RENDERED),
    gap("bash", "foreground-no-output", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-no-output", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-no-output", "/typedResult/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-stderr-only", "/modelText", US_306, WHY_RENDERED),
    gap("bash", "foreground-stderr-only", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-stderr-only", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-stderr-only", "/typedResult/output", US_306, WHY_LINE_ENDINGS),
    gap("bash", "foreground-stderr-only", "/typedResult/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-multiline-output", "/modelText", US_306, WHY_RENDERED),
    gap("bash", "foreground-multiline-output", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-multiline-output", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-multiline-output", "/typedResult/output", US_306, WHY_LINE_ENDINGS),
    gap("bash", "foreground-multiline-output", "/typedResult/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-multibyte-output", "/modelText", US_306, WHY_RENDERED),
    gap("bash", "foreground-multibyte-output", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-multibyte-output", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-multibyte-output", "/typedResult/output", US_306, WHY_LINE_ENDINGS),
    gap("bash", "foreground-multibyte-output", "/typedResult/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-output-exceeds-window", "/modelText", US_306, WHY_RENDERED),
    gap("bash", "foreground-output-exceeds-window", "/sessions/0/manifest/reader_error", US_306, WHY_TRUNCATED_READER),
    gap("bash", "foreground-output-exceeds-window", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-output-exceeds-window", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-output-exceeds-window", "/sessions/0/sessionInfo/reader_error", US_306, WHY_TRUNCATED_READER),
    gap("bash", "foreground-output-exceeds-window", "/typedResult/next_cursor", US_301, WHY_MANAGED_WINDOW),
    gap("bash", "foreground-output-exceeds-window", "/typedResult/output", US_301, WHY_MANAGED_WINDOW),
    gap("bash", "foreground-output-exceeds-window", "/typedResult/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-output-exceeds-window", "/typedResult/stdout", US_301, WHY_MANAGED_WINDOW),
    gap("bash", "foreground-output-exceeds-window", "/typedResult/truncated", US_301, WHY_MANAGED_WINDOW),
    gap("bash", "foreground-exit-non-zero", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-exit-non-zero", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-cwd-override", "/modelText", US_306, WHY_RENDERED),
    gap("bash", "foreground-cwd-override", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-cwd-override", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-cwd-override", "/typedResult/output", US_306, WHY_LINE_ENDINGS),
    gap("bash", "foreground-cwd-override", "/typedResult/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-env-override", "/modelText", US_306, WHY_RENDERED),
    gap("bash", "foreground-env-override", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-env-override", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-env-override", "/typedResult/output", US_306, WHY_LINE_ENDINGS),
    gap("bash", "foreground-env-override", "/typedResult/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-shell-override", "/modelText", US_306, WHY_RENDERED),
    gap("bash", "foreground-shell-override", "/typedResult/output", US_306, WHY_LINE_ENDINGS),
    gap("bash", "foreground-empty-command", "/error/type", US_306, WHY_ERROR_KIND),
    gap("bash", "foreground-legacy-timeout-field", "/modelText", US_306, WHY_RENDERED),
    gap("bash", "foreground-legacy-timeout-field", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-legacy-timeout-field", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-legacy-timeout-field", "/typedResult/output", US_306, WHY_LINE_ENDINGS),
    gap("bash", "foreground-legacy-timeout-field", "/typedResult/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-timeout-clamped-to-maximum", "/modelText", US_306, WHY_RENDERED),
    gap("bash", "foreground-timeout-clamped-to-maximum", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-timeout-clamped-to-maximum", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-timeout-clamped-to-maximum", "/typedResult/output", US_306, WHY_LINE_ENDINGS),
    gap("bash", "foreground-timeout-clamped-to-maximum", "/typedResult/shell", US_306, WHY_SHELL),
    gap("bash", "background-returns-immediately", "/modelText", US_306, WHY_RENDERED),
    gap("bash", "background-returns-immediately", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "background-returns-immediately", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "background-returns-immediately", "/typedResult/shell", US_306, WHY_SHELL),
    gap("bash", "soft-timeout-backgrounds-the-session", "/modelText", US_306, WHY_RENDERED),
    gap("bash", "soft-timeout-backgrounds-the-session", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "soft-timeout-backgrounds-the-session", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "soft-timeout-backgrounds-the-session", "/typedResult/shell", US_306, WHY_SHELL),
    gap("bash", "hard-timeout-kills-the-session", "/sessions/0/manifest/exit_code", US_306, WHY_SIGNAL_EXIT),
    gap("bash", "hard-timeout-kills-the-session", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "hard-timeout-kills-the-session", "/sessions/0/sessionInfo/exit_code", US_306, WHY_SIGNAL_EXIT),
    gap("bash", "hard-timeout-kills-the-session", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "background-poll-source", "/modelText", US_306, WHY_RENDERED),
    gap("bash", "background-poll-source", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "background-poll-source", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "background-poll-source", "/typedResult/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-before-any-output", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-before-any-output", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-before-any-output-with-max-bytes", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-before-any-output-with-max-bytes", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-negative-cursor", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-negative-cursor", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-zero-max-bytes", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-zero-max-bytes", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-waits-for-the-session-to-exit", "/modelText", US_306, WHY_RENDERED),
    gap("bash_output", "poll-waits-for-the-session-to-exit", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-waits-for-the-session-to-exit", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-waits-for-the-session-to-exit", "/typedResult/output", US_306, WHY_LINE_ENDINGS),
    gap("bash_output", "poll-after-completion", "/modelText", US_306, WHY_RENDERED),
    gap("bash_output", "poll-after-completion", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-after-completion", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-after-completion", "/typedResult/output", US_306, WHY_LINE_ENDINGS),
    gap("bash_output", "poll-from-a-cursor", "/modelText", US_306, WHY_RENDERED),
    gap("bash_output", "poll-from-a-cursor", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-from-a-cursor", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-from-a-cursor", "/typedResult/output", US_306, WHY_LINE_ENDINGS),
    gap("bash_output", "poll-from-a-cursor-past-the-end", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-from-a-cursor-past-the-end", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-with-max-bytes", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-with-max-bytes", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-with-the-max-chars-alias", "/modelText", US_306, WHY_RENDERED),
    gap("bash_output", "poll-with-the-max-chars-alias", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-with-the-max-chars-alias", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-with-the-max-chars-alias", "/typedResult/next_cursor", US_306, WHY_MAX_CHARS),
    gap("bash_output", "poll-with-the-max-chars-alias", "/typedResult/output", US_306, WHY_MAX_CHARS),
    gap("bash_output", "poll-with-the-max-chars-alias", "/typedResult/truncated", US_306, WHY_MAX_CHARS),
    gap("bash_output", "poll-wait-clamped-to-the-maximum", "/modelText", US_306, WHY_RENDERED),
    gap("bash_output", "poll-wait-clamped-to-the-maximum", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-wait-clamped-to-the-maximum", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_output", "poll-wait-clamped-to-the-maximum", "/typedResult/output", US_306, WHY_LINE_ENDINGS),
    gap("bash", "background-input-target", "/modelText", US_306, WHY_RENDERED),
    gap("bash", "background-input-target", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "background-input-target", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "background-input-target", "/typedResult/shell", US_306, WHY_SHELL),
    gap("bash_stdin", "write-text-to-a-running-session", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_stdin", "write-text-to-a-running-session", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_stdin", "write-multibyte-text", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_stdin", "write-multibyte-text", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_stdin", "write-base64-bytes", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_stdin", "write-base64-bytes", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_stdin", "write-a-control-key", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_stdin", "write-a-control-key", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_stdin", "write-two-control-keys", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_stdin", "write-two-control-keys", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_stdin", "write-an-empty-text", "/outcome", US_306, WHY_EMPTY_ARGUMENT),
    gap("bash_stdin", "write-nothing", "/error/type", US_306, WHY_ERROR_KIND),
    gap("bash_stdin", "write-nothing", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_stdin", "write-nothing", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_stdin", "write-text-and-control-together", "/error/type", US_306, WHY_ERROR_KIND),
    gap("bash_stdin", "write-text-and-control-together", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_stdin", "write-text-and-control-together", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_stdin", "write-an-unknown-control-key", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_stdin", "write-an-unknown-control-key", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_stdin", "write-invalid-base64", "/error/type", US_306, WHY_ERROR_KIND),
    gap("bash_stdin", "write-invalid-base64", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_stdin", "write-invalid-base64", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-input-target-exits", "/modelText", US_306, WHY_RENDERED),
    gap("bash", "foreground-input-target-exits", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-input-target-exits", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-input-target-exits", "/typedResult/shell", US_306, WHY_SHELL),
    gap("bash_stdin", "write-to-a-session-that-exited", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_stdin", "write-to-a-session-that-exited", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_sessions", "inspect-without-a-session-id", "/error/type", US_306, WHY_ERROR_KIND),
    gap("bash_sessions", "kill-without-a-session-id", "/error/type", US_306, WHY_ERROR_KIND),
    gap("bash_sessions", "reset-with-no-session", "/modelText", LICENSING, WHY_RENDERED),
    gap("bash_sessions", "reset-with-no-session", "/typedResult/message", LICENSING, WHY_MESSAGE),
    gap("bash_sessions", "reset-with-clear-logs-and-no-session", "/modelText", LICENSING, WHY_RENDERED),
    gap("bash_sessions", "reset-with-clear-logs-and-no-session", "/typedResult/message", LICENSING, WHY_MESSAGE),
    gap("bash", "background-first-session", "/modelText", US_306, WHY_RENDERED),
    gap("bash", "background-first-session", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "background-first-session", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "background-first-session", "/typedResult/shell", US_306, WHY_SHELL),
    gap("bash", "background-second-session", "/modelText", US_306, WHY_RENDERED),
    gap("bash", "background-second-session", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "background-second-session", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "background-second-session", "/typedResult/shell", US_306, WHY_SHELL),
    gap("bash_sessions", "list-two-sessions", "/modelText", US_306, WHY_RENDERED),
    gap("bash_sessions", "list-two-sessions", "/typedResult/sessions/0/shell", US_306, WHY_SHELL),
    gap("bash_sessions", "list-two-sessions", "/typedResult/sessions/1/shell", US_306, WHY_SHELL),
    gap("bash_sessions", "inspect-a-running-session", "/modelText", US_306, WHY_RENDERED),
    gap("bash_sessions", "inspect-a-running-session", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_sessions", "inspect-a-running-session", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_sessions", "inspect-a-running-session", "/typedResult/session/shell", US_306, WHY_SHELL),
    gap("bash_sessions", "inspect-with-max-bytes", "/modelText", US_306, WHY_RENDERED),
    gap("bash_sessions", "inspect-with-max-bytes", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_sessions", "inspect-with-max-bytes", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_sessions", "inspect-with-max-bytes", "/typedResult/session/shell", US_306, WHY_SHELL),
    gap("bash_sessions", "inspect-with-the-max-chars-alias", "/modelText", US_306, WHY_RENDERED),
    gap("bash_sessions", "inspect-with-the-max-chars-alias", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_sessions", "inspect-with-the-max-chars-alias", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_sessions", "inspect-with-the-max-chars-alias", "/typedResult/session/shell", US_306, WHY_SHELL),
    gap("bash_sessions", "kill-a-running-session", "/modelText", LICENSING, WHY_RENDERED),
    gap("bash_sessions", "kill-a-running-session", "/sessions/0/manifest/exit_code", US_306, WHY_SIGNAL_EXIT),
    gap("bash_sessions", "kill-a-running-session", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_sessions", "kill-a-running-session", "/sessions/0/sessionInfo", US_306, WHY_KILLED_SESSION),
    gap("bash_sessions", "kill-a-running-session", "/typedResult/message", LICENSING, WHY_MESSAGE),
    gap("bash_sessions", "kill-a-running-session", "/typedResult/session/shell", US_306, WHY_SHELL),
    gap("bash_sessions", "kill-a-running-session", "/typedResult/session/exit_code", US_306, WHY_SIGNAL_EXIT),
    gap("bash_sessions", "list-after-a-kill", "/modelText/described", US_306, WHY_RENDERED),
    gap("bash_sessions", "list-after-a-kill", "/modelText/length", US_306, WHY_RENDERED),
    gap("bash_sessions", "list-after-a-kill", "/typedResult/sessions", US_306, WHY_KILLED_SESSION),
    gap("bash_sessions", "inspect-a-killed-session", "/outcome", US_306, WHY_KILLED_SESSION),
    gap("bash_sessions", "kill-an-already-killed-session", "/outcome", US_306, WHY_KILLED_SESSION),
    gap("bash_sessions", "reset-the-remaining-session", "/modelText", LICENSING, WHY_RENDERED),
    gap("bash_sessions", "reset-the-remaining-session", "/typedResult/message", LICENSING, WHY_MESSAGE),
    gap("bash_sessions", "reset-the-remaining-session", "/typedResult/sessions/0/exit_code", US_306, WHY_SIGNAL_EXIT),
    gap("bash_sessions", "reset-the-remaining-session", "/typedResult/sessions/0/shell", US_306, WHY_SHELL),
    gap("bash_sessions", "list-after-a-reset", "/modelText/described", US_306, WHY_RENDERED),
    gap("bash_sessions", "list-after-a-reset", "/modelText/length", US_306, WHY_RENDERED),
    gap("bash_sessions", "list-after-a-reset", "/typedResult/sessions", US_306, WHY_KILLED_SESSION),
    gap("bash_sessions", "reset-and-clear-the-logs", "/modelText", LICENSING, WHY_RENDERED),
    gap("bash_sessions", "reset-and-clear-the-logs", "/typedResult/message", LICENSING, WHY_MESSAGE),
    gap("bash", "foreground-log-source", "/modelText", US_306, WHY_RENDERED),
    gap("bash", "foreground-log-source", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-log-source", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "foreground-log-source", "/typedResult/output", US_306, WHY_LINE_ENDINGS),
    gap("bash", "foreground-log-source", "/typedResult/shell", US_306, WHY_SHELL),
    gap("bash_log_file", "read-a-session-log-from-the-start", "/modelText", US_306, WHY_RENDERED),
    gap("bash_log_file", "read-a-session-log-from-the-start", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_log_file", "read-a-session-log-from-the-start", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_log_file", "read-a-session-log-from-the-start", "/typedResult/content", US_306, WHY_LINE_ENDINGS),
    gap("bash_log_file", "read-with-max-bytes", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_log_file", "read-with-max-bytes", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_log_file", "read-with-the-max-chars-alias", "/modelText", US_306, WHY_RENDERED),
    gap("bash_log_file", "read-with-the-max-chars-alias", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_log_file", "read-with-the-max-chars-alias", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_log_file", "read-with-the-max-chars-alias", "/typedResult/content", US_306, WHY_MAX_CHARS),
    gap("bash_log_file", "read-with-the-max-chars-alias", "/typedResult/next_cursor", US_306, WHY_MAX_CHARS),
    gap("bash_log_file", "read-with-the-max-chars-alias", "/typedResult/truncated", US_306, WHY_MAX_CHARS),
    gap("bash_log_file", "read-from-an-offset", "/modelText", US_306, WHY_RENDERED),
    gap("bash_log_file", "read-from-an-offset", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_log_file", "read-from-an-offset", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_log_file", "read-from-an-offset", "/typedResult/content", US_306, WHY_LINE_ENDINGS),
    gap("bash_log_file", "read-from-an-offset-past-the-end", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_log_file", "read-from-an-offset-past-the-end", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_log_file", "read-a-log-that-was-deleted", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_log_file", "read-a-log-that-was-deleted", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_log_file", "read-a-negative-offset", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_log_file", "read-a-negative-offset", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_log_file", "read-by-relative-path", "/modelText", US_306, WHY_RENDERED),
    gap("bash_log_file", "read-by-relative-path", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_log_file", "read-by-relative-path", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash_log_file", "read-by-relative-path", "/typedResult/content", US_306, WHY_LINE_ENDINGS),
    gap("bash_log_file", "read-without-a-session-or-a-path", "/error/type", US_306, WHY_ERROR_KIND),
    gap("bash_log_file", "write-without-content", "/outcome", US_306, WHY_EMPTY_ARGUMENT),
    gap("bash", "background-live-log-source", "/modelText", US_306, WHY_RENDERED),
    gap("bash", "background-live-log-source", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash", "background-live-log-source", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
    gap("bash", "background-live-log-source", "/typedResult/shell", US_306, WHY_SHELL),
    gap("bash_log_file", "write-to-a-live-session-log", "/sessions/0/manifest/shell", US_306, WHY_SHELL),
    gap("bash_log_file", "write-to-a-live-session-log", "/sessions/0/sessionInfo/shell", US_306, WHY_SHELL),
];
