"""Declarative parity scenarios recorded against the Python reference.

Each scenario names the audited gap it proves. ``oracle.py`` refuses to write a
corpus when a gap has no scenario, so this file is the single place where the
audited surface is enumerated.
"""

from __future__ import annotations

from typing import Any

GAPS: list[dict[str, str]] = [
    {
        "id": "GAP-01",
        "story": "US-004",
        "title": "Input modes, prefix rendering and completion source",
    },
    {
        "id": "GAP-02",
        "story": "US-004",
        "title": "Submission stripping and empty-turn suppression",
    },
    {
        "id": "GAP-03",
        "story": "US-004",
        "title": "Mode removal on backspace and teleport gating",
    },
    {
        "id": "GAP-04",
        "story": "US-005",
        "title": "Unicode cursor, selection and word editing",
    },
    {
        "id": "GAP-05",
        "story": "US-005",
        "title": "External editor round-trip state",
    },
    {
        "id": "GAP-06",
        "story": "US-006",
        "title": "Persistent bounded prompt history",
    },
    {
        "id": "GAP-07",
        "story": "US-007",
        "title": "Visual-line history navigation and draft restoration",
    },
    {
        "id": "GAP-08",
        "story": "US-008",
        "title": "Command registry, aliases, availability and Rust-only surface",
    },
    {
        "id": "GAP-09",
        "story": "US-009",
        "title": "Slash ranking, promotion boosts and skill metadata",
    },
    {
        "id": "GAP-10",
        "story": "US-009",
        "title": "Slash popup control keys and dismissal",
    },
    {
        "id": "GAP-11",
        "story": "US-010",
        "title": "Path completion trigger range and query semantics",
    },
    {
        "id": "GAP-12",
        "story": "US-010",
        "title": "Indexed corpus, ignores and deterministic order",
    },
    {
        "id": "GAP-13",
        "story": "US-011",
        "title": "Asynchronous completion generations and cancellation",
    },
    {
        "id": "GAP-14",
        "story": "US-011",
        "title": "Completion popup rendering and bounds",
    },
    {
        "id": "GAP-15",
        "story": "US-012",
        "title": "Atomic paste without shortcut dispatch",
    },
    {
        "id": "GAP-16",
        "story": "US-012",
        "title": "Drag-and-drop image path normalization",
    },
    {
        "id": "GAP-17",
        "story": "US-013",
        "title": "Mention submission semantics",
    },
    {
        "id": "GAP-18",
        "story": "US-014",
        "title": "Clipboard image triggers and lifecycle",
    },
    {
        "id": "GAP-19",
        "story": "US-016",
        "title": "Voice recording state and transcript insertion",
    },
    {
        "id": "GAP-20",
        "story": "US-017",
        "title": "Feedback, safety and model-switching chrome",
    },
    {
        "id": "GAP-21",
        "story": "US-018",
        "title": "Long prompt viewport and cursor reachability",
    },
]


def key(name: str, *mods: str) -> dict[str, Any]:
    return {"type": "key", "key": name, "mods": list(mods)}


def char(value: str, *mods: str) -> dict[str, Any]:
    return {"type": "key", "key": "char", "char": value, "mods": list(mods)}


def text(value: str) -> dict[str, Any]:
    return {"type": "text", "text": value}


def paste(value: str) -> dict[str, Any]:
    return {"type": "paste", "text": value}


def mouse(x: int, y: int, *, extend_selection: bool = False) -> dict[str, Any]:
    return {
        "type": "mouse",
        "x": x,
        "y": y,
        "extendSelection": extend_selection,
    }


SKILLS = [
    {"command": "/review", "description": "Review the working tree"},
    {"command": "/changelog", "description": "Draft a changelog entry"},
]


SCENARIOS: list[dict[str, Any]] = [
    # -- GAP-01: input modes ------------------------------------------------
    {
        "id": "modes-slash-prefix",
        "gap": "GAP-01",
        "story": "US-004",
        "title": "Leading slash switches to command mode and keeps text unprefixed",
        "events": [char("/"), text("cl")],
    },
    {
        "id": "modes-bang-prefix",
        "gap": "GAP-01",
        "story": "US-004",
        "title": "Leading bang switches to shell mode",
        "events": [char("!"), text("ls -la")],
    },
    {
        "id": "modes-teleport-available",
        "gap": "GAP-01",
        "story": "US-004",
        "title": "Ampersand switches to teleport mode when the command exists",
        "commands": {"vibeCodeEnabled": True},
        "events": [char("&"), text("target")],
    },
    {
        "id": "modes-prompt-default",
        "gap": "GAP-01",
        "story": "US-004",
        "title": "Mode characters typed after text stay literal",
        "events": [text("note /help and !ls")],
    },
    # -- GAP-02: submission -------------------------------------------------
    {
        "id": "submit-strips-whitespace",
        "gap": "GAP-02",
        "story": "US-004",
        "title": "Submitted text is stripped on both ends",
        "events": [text("   spaced prompt   "), key("enter")],
    },
    {
        "id": "submit-whitespace-only",
        "gap": "GAP-02",
        "story": "US-004",
        "title": "A whitespace-only prompt submits an empty value and keeps state",
        "events": [text("   "), key("enter")],
    },
    {
        "id": "submit-empty-composer",
        "gap": "GAP-02",
        "story": "US-004",
        "title": "Enter on an empty composer still emits an empty submission",
        "events": [key("enter")],
    },
    {
        "id": "submit-multiline-shift-enter",
        "gap": "GAP-02",
        "story": "US-004",
        "title": "Shift+Enter inserts a newline instead of submitting",
        "events": [text("first"), key("enter", "shift"), text("second"), key("enter")],
    },
    # -- GAP-03: mode removal ----------------------------------------------
    {
        "id": "mode-backspace-resets",
        "gap": "GAP-03",
        "story": "US-004",
        "title": "Backspace on an empty command mode returns to prompt mode",
        "events": [char("/"), key("backspace"), text("plain")],
    },
    {
        "id": "mode-backspace-keeps-text",
        "gap": "GAP-03",
        "story": "US-004",
        "title": "Backspace inside command text deletes characters before the mode",
        "events": [char("/"), text("ab"), key("backspace"), key("backspace"), key("backspace")],
    },
    {
        "id": "mode-teleport-unavailable",
        "gap": "GAP-03",
        "story": "US-004",
        "title": "Ampersand stays literal when teleport is excluded",
        "commands": {"excluded": ["teleport"]},
        "events": [char("&"), text("target")],
    },
    # -- GAP-04: unicode editing -------------------------------------------
    {
        "id": "unicode-combining-backspace",
        "gap": "GAP-04",
        "story": "US-005",
        "title": "Backspace over a combining sequence",
        "events": [text("aéb"), key("backspace"), key("backspace")],
    },
    {
        "id": "unicode-emoji-motion",
        "gap": "GAP-04",
        "story": "US-005",
        "title": "Left and right motion across an emoji sequence",
        "events": [
            text("a\U0001f469‍\U0001f4bbb"),
            key("left"),
            key("left"),
            key("right"),
        ],
    },
    {
        "id": "unicode-wide-characters",
        "gap": "GAP-04",
        "story": "US-005",
        "title": "Cursor cells across double-width characters",
        "events": [text("你好 world"), key("home"), key("right"), key("right")],
    },
    {
        "id": "unicode-word-motion",
        "gap": "GAP-04",
        "story": "US-005",
        "title": "Alt+Left and Alt+Right move by word",
        "events": [text("alpha beta gamma"), key("left", "alt"), key("left", "alt"), key("right", "alt")],
    },
    {
        "id": "unicode-shift-selection",
        "gap": "GAP-04",
        "story": "US-005",
        "title": "Shift selection then replacement",
        "events": [text("select me"), key("home"), key("right", "shift"), key("right", "shift"), text("X")],
    },
    {
        "id": "unicode-home-end",
        "gap": "GAP-04",
        "story": "US-005",
        "title": "Home and End on a wrapped multiline prompt",
        "events": [text("first line"), key("enter", "shift"), text("second line"), key("home"), key("end")],
    },
    {
        "id": "mouse-click-wide-character",
        "gap": "GAP-04",
        "story": "US-005",
        "title": "A mouse click maps terminal cells across a wide character",
        "events": [text("a界b"), mouse(2, 0)],
    },
    {
        "id": "mouse-shift-selection",
        "gap": "GAP-04",
        "story": "US-005",
        "title": "A shifted mouse click extends the current selection",
        "events": [text("select me"), mouse(2, 0), mouse(7, 0, extend_selection=True)],
    },
    {
        "id": "mouse-out-of-bounds",
        "gap": "GAP-04",
        "story": "US-005",
        "title": "An out-of-bounds mouse target leaves the prompt unchanged",
        "events": [text("stable"), mouse(999, 999)],
    },
    # -- GAP-05: external editor -------------------------------------------
    {
        "id": "external-editor-replaces-text",
        "gap": "GAP-05",
        "story": "US-005",
        "title": "External editor output replaces the prompt and resets navigation",
        "events": [text("draft"), {"type": "externalEditor", "text": "edited\nsecond"}],
    },
    {
        "id": "external-editor-unchanged",
        "gap": "GAP-05",
        "story": "US-005",
        "title": "Unchanged external editor output preserves the prompt",
        "events": [text("draft"), {"type": "externalEditor", "text": "draft"}],
    },
    {
        "id": "external-editor-refreshes-completion",
        "gap": "GAP-05",
        "story": "US-005",
        "title": "External editor output refreshes completion for its new token",
        "events": [text("draft"), {"type": "externalEditor", "text": "/c"}],
    },
    # -- GAP-06: persistent history ----------------------------------------
    {
        "id": "history-persists-submission",
        "gap": "GAP-06",
        "story": "US-006",
        "title": "A successful submission is appended to the history file",
        "history": {"entries": []},
        "events": [text("first prompt"), key("enter"), text("second prompt"), key("enter")],
    },
    {
        "id": "history-suppresses-duplicates",
        "gap": "GAP-06",
        "story": "US-006",
        "title": "Consecutive duplicates are not persisted twice",
        "history": {"entries": ["same prompt"]},
        "events": [text("same prompt"), key("enter")],
    },
    {
        "id": "history-loads-existing",
        "gap": "GAP-06",
        "story": "US-006",
        "title": "Existing entries are recalled in reference order",
        "history": {"entries": ["oldest", "middle", "newest"]},
        "events": [key("up"), key("up"), key("up"), key("up")],
    },
    {
        "id": "history-tolerates-corrupt-lines",
        "gap": "GAP-06",
        "story": "US-006",
        "title": "Corrupt history lines are loaded as raw text without failing",
        "history": {"raw": '"valid entry"\nnot json\n"another entry"\n'},
        "events": [key("up"), key("up")],
    },
    # -- GAP-07: visual-line history ---------------------------------------
    {
        "id": "history-up-moves-inside-multiline",
        "gap": "GAP-07",
        "story": "US-007",
        "title": "Up moves within a hard multiline prompt before recalling history",
        "history": {"entries": ["recalled"]},
        "events": [
            text("line one"),
            key("enter", "shift"),
            text("line two"),
            key("up"),
            key("up"),
        ],
    },
    {
        "id": "history-up-from-first-line",
        "gap": "GAP-07",
        "story": "US-007",
        "title": "Up on the first visual line recalls history",
        "history": {"entries": ["recalled"]},
        "events": [text("draft"), key("home"), key("up")],
    },
    {
        "id": "history-down-restores-draft",
        "gap": "GAP-07",
        "story": "US-007",
        "title": "Down past the newest entry restores the draft",
        "history": {"entries": ["older", "newer"]},
        "events": [text("draft"), key("home"), key("up"), key("up"), key("down"), key("down")],
    },
    {
        "id": "history-edit-after-recall",
        "gap": "GAP-07",
        "story": "US-007",
        "title": "Editing a recalled entry resets history navigation",
        "history": {"entries": ["recalled entry"]},
        "events": [key("up"), text("!"), key("up")],
    },
    {
        "id": "history-wrapped-line-navigation",
        "gap": "GAP-07",
        "story": "US-007",
        "title": "Up inside a soft-wrapped line moves visually before recalling",
        "viewport": {"width": 40, "height": 24},
        "history": {"entries": ["recalled"]},
        "events": [
            text("wrapped prompt that is long enough to soft wrap across lines"),
            key("up"),
            key("up"),
            key("up"),
        ],
    },
    # -- GAP-08: command registry ------------------------------------------
    {
        "id": "commands-full-surface",
        "gap": "GAP-08",
        "story": "US-008",
        "title": "The complete alias surface is offered for a bare slash",
        "events": [char("/")],
    },
    {
        "id": "commands-vibe-code-enabled",
        "gap": "GAP-08",
        "story": "US-008",
        "title": "Vibe Code commands appear when the capability is enabled",
        "commands": {"vibeCodeEnabled": True},
        "events": [char("/")],
    },
    {
        "id": "commands-excluded",
        "gap": "GAP-08",
        "story": "US-008",
        "title": "Excluded commands disappear from discovery",
        "commands": {"excluded": ["teleport", "voice"]},
        "events": [char("/")],
    },
    {
        "id": "commands-unknown-alias",
        "gap": "GAP-08",
        "story": "US-008",
        "title": "A Rust-only alias has no reference suggestion",
        "events": [char("/"), text("fork")],
    },
    {
        "id": "commands-clipboard-image-supported",
        "gap": "GAP-08",
        "story": "US-008",
        "title": "Clipboard image support publishes the paste-image alias",
        "capabilities": ["macos-clipboard"],
        "events": [char("/"), text("pas")],
    },
    # -- GAP-09: slash ranking ---------------------------------------------
    {
        "id": "slash-ranking-c",
        "gap": "GAP-09",
        "story": "US-009",
        "title": "The /c query promotes config over clear",
        "events": [char("/"), text("c")],
    },
    {
        "id": "slash-ranking-empty-boosts",
        "gap": "GAP-09",
        "story": "US-009",
        "title": "An empty query promotes help then config",
        "events": [char("/")],
    },
    {
        "id": "slash-ranking-fuzzy",
        "gap": "GAP-09",
        "story": "US-009",
        "title": "Fuzzy subsequence ranking for a sparse query",
        "events": [char("/"), text("cnt")],
    },
    {
        "id": "slash-skill-entries",
        "gap": "GAP-09",
        "story": "US-009",
        "title": "Skills join the command surface with their descriptions",
        "skills": SKILLS,
        "events": [char("/"), text("re")],
    },
    {
        "id": "slash-no-match",
        "gap": "GAP-09",
        "story": "US-009",
        "title": "A query with no match closes the popup",
        "events": [char("/"), text("zzzz")],
    },
    {
        "id": "slash-double-marker",
        "gap": "GAP-09",
        "story": "US-009",
        "title": "A doubled marker keeps its second slash inside the query",
        "events": [char("/"), char("/")],
    },
    {
        "id": "slash-uppercase-alias",
        "gap": "GAP-09",
        "story": "US-009",
        "title": "An alias typed in uppercase still ranks",
        "events": [char("/"), text("CL")],
    },
    # -- GAP-10: popup control ---------------------------------------------
    {
        "id": "slash-popup-arrows",
        "gap": "GAP-10",
        "story": "US-009",
        "title": "Down and Up cycle the slash selection",
        "events": [char("/"), text("c"), key("down"), key("down"), key("up")],
    },
    {
        "id": "slash-popup-tab-applies",
        "gap": "GAP-10",
        "story": "US-009",
        "title": "Tab applies the selected command without submitting",
        "events": [char("/"), text("c"), key("tab")],
    },
    {
        "id": "slash-popup-enter-submits",
        "gap": "GAP-10",
        "story": "US-009",
        "title": "Enter applies the selection and submits",
        "events": [char("/"), text("c"), key("enter")],
    },
    {
        "id": "slash-popup-escape",
        "gap": "GAP-10",
        "story": "US-009",
        "title": "Escape is not consumed by the slash popup",
        "events": [char("/"), text("c"), key("escape"), text("o")],
    },
    {
        "id": "slash-popup-right",
        "gap": "GAP-10",
        "story": "US-009",
        "title": "Right moves the cursor instead of accepting",
        "events": [char("/"), text("c"), key("left"), key("right")],
    },
    {
        "id": "slash-popup-wraps-selection",
        "gap": "GAP-10",
        "story": "US-009",
        "title": "Up from the first item wraps to the last",
        "events": [char("/"), text("c"), key("up")],
    },
    {
        "id": "slash-popup-caret-at-line-start",
        "gap": "GAP-10",
        "story": "US-009",
        "title": "Home stops at the mode marker and leaves the popup ranked",
        "events": [char("/"), text("cl"), key("home")],
    },
    {
        "id": "slash-popup-mid-token-cursor",
        "gap": "GAP-10",
        "story": "US-009",
        "title": "A mid-token caret bounds the query and the replacement",
        "events": [
            text("/mp add x"),
            key("left"),
            key("left"),
            key("left"),
            key("left"),
            key("left"),
            key("left"),
            key("left"),
            char("c"),
            key("tab"),
        ],
    },
    # -- GAP-11: path triggers ---------------------------------------------
    {
        "id": "path-trigger-basic",
        "gap": "GAP-11",
        "story": "US-010",
        "title": "An @ token opens path completion",
        "workspace": "sample",
        "events": [text("inspect @not")],
    },
    {
        "id": "path-trigger-after-punctuation",
        "gap": "GAP-11",
        "story": "US-010",
        "title": "The last @ before the cursor wins even after punctuation",
        "workspace": "sample",
        "events": [text("see(@src")],
    },
    {
        "id": "path-trigger-nested",
        "gap": "GAP-11",
        "story": "US-010",
        "title": "A nested path lists immediate children",
        "workspace": "sample",
        "events": [text("open @src/")],
    },
    {
        "id": "path-trigger-space-closes",
        "gap": "GAP-11",
        "story": "US-010",
        "title": "A space after the token closes path completion",
        "workspace": "sample",
        "events": [text("open @src"), text(" ")],
    },
    {
        "id": "path-trigger-bare-at",
        "gap": "GAP-11",
        "story": "US-010",
        "title": "A bare @ lists top-level entries only",
        "workspace": "sample",
        "events": [char("@")],
    },
    {
        "id": "path-accept-inserts-space",
        "gap": "GAP-11",
        "story": "US-010",
        "title": "Accepting a file mention appends a single space",
        "workspace": "sample",
        "events": [text("inspect @notes"), key("tab")],
    },
    {
        "id": "path-accept-directory",
        "gap": "GAP-11",
        "story": "US-010",
        "title": "Accepting a directory keeps the trailing slash without a space",
        "workspace": "sample",
        "events": [text("inspect @src"), key("tab")],
    },
    {
        "id": "path-mid-token-completion",
        "gap": "GAP-11",
        "story": "US-010",
        "title": "Completion replaces only up to the cursor",
        "workspace": "sample",
        "events": [text("inspect @notesXY"), key("left"), key("left"), key("tab")],
    },
    # -- GAP-12: indexed corpus --------------------------------------------
    {
        "id": "corpus-hidden-files",
        "gap": "GAP-12",
        "story": "US-010",
        "title": "Hidden entries stay out until the query starts with a dot",
        "workspace": "sample",
        "events": [text("show @hidden")],
    },
    {
        "id": "corpus-dot-query",
        "gap": "GAP-12",
        "story": "US-010",
        "title": "A dot query exposes hidden entries",
        "workspace": "sample",
        "events": [text("show @.hid")],
    },
    {
        "id": "corpus-gitignore",
        "gap": "GAP-12",
        "story": "US-010",
        "title": "Ignored paths are absent from the corpus",
        "workspace": "sample",
        "events": [text("show @secret")],
    },
    {
        "id": "corpus-nested-ranking",
        "gap": "GAP-12",
        "story": "US-010",
        "title": "Nested matches are ranked deterministically",
        "workspace": "sample",
        "events": [text("show @rs")],
    },
    # -- GAP-13: async generations -----------------------------------------
    {
        "id": "async-generation-supersedes",
        "gap": "GAP-13",
        "story": "US-011",
        "title": "Rapid edits only surface the newest query results",
        "workspace": "sample",
        "events": [text("@s"), text("r"), text("c")],
    },
    {
        "id": "async-cancelled-by-space",
        "gap": "GAP-13",
        "story": "US-011",
        "title": "A trailing space cancels the pending query",
        "workspace": "sample",
        "events": [text("@src"), text(" ")],
    },
    {
        "id": "async-history-recall-closes",
        "gap": "GAP-13",
        "story": "US-011",
        "title": "History recall closes completion",
        "workspace": "sample",
        "history": {"entries": ["recalled"]},
        "events": [text("@src"), key("home"), key("up")],
    },
    # -- GAP-14: popup rendering -------------------------------------------
    {
        "id": "popup-render-80",
        "gap": "GAP-14",
        "story": "US-011",
        "title": "Slash popup rendering at 80 columns",
        "viewport": {"width": 80, "height": 24},
        "events": [char("/"), text("co")],
    },
    {
        "id": "popup-render-40",
        "gap": "GAP-14",
        "story": "US-011",
        "title": "Slash popup rendering at 40 columns",
        "viewport": {"width": 40, "height": 24},
        "events": [char("/"), text("co")],
    },
    {
        "id": "popup-render-120",
        "gap": "GAP-14",
        "story": "US-011",
        "title": "Slash popup rendering at 120 columns",
        "viewport": {"width": 120, "height": 24},
        "events": [char("/"), text("co")],
    },
    {
        "id": "popup-render-path-bound",
        "gap": "GAP-14",
        "story": "US-011",
        "title": "Path popup is bounded to ten rows",
        "workspace": "sample",
        "events": [char("@")],
    },
    # -- GAP-15: atomic paste ----------------------------------------------
    {
        "id": "paste-multiline-atomic",
        "gap": "GAP-15",
        "story": "US-012",
        "title": "A multiline paste is inserted as one edit",
        "events": [paste("first line\nsecond line\n\tindented")],
    },
    {
        "id": "paste-control-characters",
        "gap": "GAP-15",
        "story": "US-012",
        "title": "Control-like payloads are inserted as text",
        "events": [paste("before\x1b[Aafter\x03end")],
    },
    {
        "id": "paste-mode-characters",
        "gap": "GAP-15",
        "story": "US-012",
        "title": "A pasted leading slash does not switch mode",
        "events": [paste("/clear should stay text")],
    },
    {
        "id": "paste-large-payload",
        "gap": "GAP-15",
        "story": "US-012",
        "title": "A payload above the Rust paste bound is accepted",
        "events": [paste("x" * (256 * 1024 + 64))],
    },
    {
        "id": "paste-empty-triggers-clipboard",
        "gap": "GAP-15",
        "story": "US-012",
        "title": "An empty paste probes the clipboard silently",
        "events": [paste("")],
    },
    # -- GAP-16: drag and drop ---------------------------------------------
    {
        "id": "dnd-absolute-image",
        "gap": "GAP-16",
        "story": "US-012",
        "title": "A pasted absolute image path becomes an @ mention",
        "workspace": "sample",
        "events": [{"type": "paste", "text": "__WORKSPACE__/image one.png"}],
    },
    {
        "id": "dnd-escaped-image",
        "gap": "GAP-16",
        "story": "US-012",
        "title": "A backslash-escaped image path is normalized",
        "workspace": "sample",
        "events": [{"type": "paste", "text": "__WORKSPACE__/image\\ one.png"}],
    },
    {
        "id": "dnd-text-path-untouched",
        "gap": "GAP-16",
        "story": "US-012",
        "title": "A non-image path is pasted verbatim",
        "workspace": "sample",
        "events": [{"type": "paste", "text": "__WORKSPACE__/notes.txt"}],
    },
    # -- GAP-17: mentions ---------------------------------------------------
    {
        "id": "mention-text-file-submission",
        "gap": "GAP-17",
        "story": "US-013",
        "title": "A text mention stays prompt text on submission",
        "workspace": "sample",
        "events": [text("summarize @notes.txt now"), key("enter")],
    },
    {
        "id": "mention-directory-submission",
        "gap": "GAP-17",
        "story": "US-013",
        "title": "A directory mention stays prompt text",
        "workspace": "sample",
        "events": [text("review @src/ please"), key("enter")],
    },
    {
        "id": "mention-missing-path-submission",
        "gap": "GAP-17",
        "story": "US-013",
        "title": "A missing mention does not block submission",
        "workspace": "sample",
        "events": [text("open @does-not-exist.txt"), key("enter")],
    },
    {
        "id": "mention-external-path-submission",
        "gap": "GAP-17",
        "story": "US-013",
        "title": "An external mention stays prompt text",
        "workspace": "sample",
        "events": [text("compare @/etc/hostname"), key("enter")],
    },
    {
        "id": "mention-image-payload-submission",
        "gap": "GAP-17",
        "story": "US-013",
        "title": "A supported image produces the canonical submission payload",
        "workspace": "sample",
        "captureSubmission": True,
        "events": [paste("inspect @'__WORKSPACE__/image one.png'"), key("enter")],
    },
    # -- GAP-18: clipboard image -------------------------------------------
    {
        "id": "clipboard-implicit-empty-paste",
        "gap": "GAP-18",
        "story": "US-014",
        "title": "An empty bracketed paste requests a silent clipboard probe",
        "events": [paste("")],
    },
    {
        "id": "clipboard-whitespace-paste",
        "gap": "GAP-18",
        "story": "US-014",
        "title": "A whitespace-only paste also probes the clipboard",
        "events": [paste("   ")],
    },
    {
        "id": "clipboard-explicit-ctrl-v",
        "gap": "GAP-18",
        "story": "US-014",
        "title": "Ctrl+V requests a notifying clipboard probe on macOS",
        "capabilities": ["macos-clipboard"],
        "events": [char("v", "ctrl")],
    },
    # -- GAP-19: voice ------------------------------------------------------
    {
        "id": "voice-start-recording",
        "gap": "GAP-19",
        "story": "US-016",
        "title": "Ctrl+R starts recording when voice is enabled",
        "voice": {"enabled": True},
        "events": [char("r", "ctrl")],
    },
    {
        "id": "voice-key-stops-recording",
        "gap": "GAP-19",
        "story": "US-016",
        "title": "Any key during recording stops it and is consumed",
        "voice": {"enabled": True},
        "events": [char("r", "ctrl"), char("a")],
    },
    {
        "id": "voice-ctrl-c-cancels",
        "gap": "GAP-19",
        "story": "US-016",
        "title": "Ctrl+C cancels an active recording",
        "voice": {"enabled": True},
        "events": [char("r", "ctrl"), char("c", "ctrl")],
    },
    {
        "id": "voice-transcript-insertion",
        "gap": "GAP-19",
        "story": "US-016",
        "title": "A transcript is inserted at the cursor",
        "voice": {"enabled": True},
        "events": [text("say: "), char("r", "ctrl"), {"type": "transcript", "text": "hello world"}],
    },
    {
        "id": "voice-disabled-ignores-key",
        "gap": "GAP-19",
        "story": "US-016",
        "title": "Ctrl+R is inert when voice is disabled",
        "voice": {"enabled": False},
        "events": [char("r", "ctrl")],
    },
    {
        "id": "voice-start-failure",
        "gap": "GAP-19",
        "story": "US-016",
        "title": "A recording start failure warns and stays idle",
        "voice": {"enabled": True, "startError": "No microphone is available"},
        "events": [char("r", "ctrl")],
    },
    # -- GAP-20: feedback, safety, switching --------------------------------
    {
        "id": "feedback-rating-keys",
        "gap": "GAP-20",
        "story": "US-017",
        "title": "Numeric keys emit ratings while feedback is active",
        "initial": {"feedbackActive": True},
        "events": [char("1")],
    },
    {
        "id": "feedback-snooze-key",
        "gap": "GAP-20",
        "story": "US-017",
        "title": "Zero snoozes feedback",
        "initial": {"feedbackActive": True},
        "events": [char("0")],
    },
    {
        "id": "feedback-other-character",
        "gap": "GAP-20",
        "story": "US-017",
        "title": "Another printable character dismisses feedback and is inserted",
        "initial": {"feedbackActive": True},
        "events": [char("a")],
    },
    {
        "id": "safety-destructive-chrome",
        "gap": "GAP-20",
        "story": "US-017",
        "title": "Destructive safety exposes its border class",
        "safety": "destructive",
        "agentName": "agent",
        "events": [text("run")],
    },
    {
        "id": "safety-transition",
        "gap": "GAP-20",
        "story": "US-017",
        "title": "Safety transitions swap the border class",
        "safety": "safe",
        "events": [{"type": "safety", "value": "yolo"}],
    },
    {
        "id": "switching-blocks-submission",
        "gap": "GAP-20",
        "story": "US-017",
        "title": "Model switching blocks submission and keeps the prompt",
        "events": [text("queued prompt"), {"type": "switching", "active": True}, key("enter")],
    },
    {
        "id": "switching-resolves",
        "gap": "GAP-20",
        "story": "US-017",
        "title": "Leaving the switching state restores submission",
        "events": [
            text("queued prompt"),
            {"type": "switching", "active": True},
            key("enter"),
            {"type": "switching", "active": False},
            key("enter"),
        ],
    },
    # -- GAP-21: long prompts ----------------------------------------------
    {
        "id": "long-prompt-viewport-80",
        "gap": "GAP-21",
        "story": "US-018",
        "title": "A long prompt keeps every grapheme and follows the cursor",
        "viewport": {"width": 80, "height": 24},
        "events": [paste("lorem ipsum dolor sit amet " * 400), key("home"), key("end")],
    },
    {
        "id": "long-prompt-viewport-40",
        "gap": "GAP-21",
        "story": "US-018",
        "title": "A long prompt wraps deterministically at 40 columns",
        "viewport": {"width": 40, "height": 24},
        "events": [paste("lorem ipsum dolor sit amet " * 400), key("home")],
    },
    {
        "id": "long-prompt-resize",
        "gap": "GAP-21",
        "story": "US-018",
        "title": "Resizing rewraps a long prompt without losing text",
        "viewport": {"width": 120, "height": 24},
        "events": [
            paste("lorem ipsum dolor sit amet " * 400),
            {"type": "resize", "width": 40, "height": 24},
            key("home"),
        ],
    },
    {
        "id": "long-prompt-unicode",
        "gap": "GAP-21",
        "story": "US-018",
        "title": "A long unicode prompt keeps valid cursor cells",
        "viewport": {"width": 40, "height": 24},
        "events": [paste("你好 \U0001f600 café\t" * 200), key("end"), key("left")],
    },
]
