complete -c vibe -s v -l version -d 'Print version'
complete -c vibe -s p -l prompt -r -d 'Run a prompt'
complete -c vibe -l output -r -a 'text json streaming' -d 'Select output mode'
complete -c vibe -l resume -r -d 'Resume a session'
complete -c vibe -s c -l continue -d 'Continue the last session'
complete -c vibe -l workdir -r -a '(__fish_complete_directories)' -d 'Set working directory'
complete -c vibe -l add-dir -r -a '(__fish_complete_directories)' -d 'Authorize another directory'
complete -c vibe -l trust -d 'Trust the working directory'
complete -c vibe -l agent -r -d 'Select agent'
complete -c vibe -l enabled-tools -r -d 'Enable a tool'
complete -c vibe -l disabled-tools -r -d 'Disable a tool'
complete -c vibe -l max-turns -r -d 'Limit turns'
complete -c vibe -l max-tokens -r -d 'Limit tokens'
complete -c vibe -l max-price -r -d 'Limit price'
complete -c vibe -l auto-approve -d 'Approve tool requests'
complete -c vibe -l yolo -d 'Approve tool requests'
complete -c vibe -l setup -d 'Run setup'
complete -c vibe -l check-upgrade -d 'Check for an update'
complete -c vibe -l worktree -r -d 'Run inside a git worktree'
complete -c vibe -s h -l help -d 'Print help'
