//! The method names the contract declares, and the predicate that answers
//! whether a name belongs to it.

/// Every method the reference declares, sorted and unique.
///
/// Reference `SERVER_METHODS` (`vibe/app_server/protocol.py`). A name belongs
/// here because the reference declares it; a request naming anything else is
/// answered `method_not_found`, as the reference answers it.
///
/// The lifecycle frames (`initialize` and the `initialized` notification) are
/// deliberately absent: they are handled before method dispatch and are not
/// part of the negotiated surface.
pub const SERVER_METHODS: [&str; 137] = [
    "account/read",
    "agents/install",
    "agents/list",
    "agents/uninstall",
    "callback/result",
    "config/fields/read",
    "config/model/write",
    "config/proxy/read",
    "config/proxy/write",
    "config/read",
    "config/reload",
    "config/schema",
    "config/write",
    "connector_catalog/auth/request",
    "connector_catalog/read",
    "connector_catalog/refresh",
    "connector_catalog/toggle",
    "connectors/auth/read",
    "connectors/read",
    "connectors/refresh",
    "diagnostics/list",
    "diagnostics/logs/read",
    "events/read",
    "feedback/record",
    "feedback/shouldShow",
    "identity/read",
    "loops/clear",
    "loops/create",
    "loops/delete",
    "loops/list",
    "mcp/add",
    "mcp/login",
    "mcp/logout",
    "mcp/read",
    "mcp/refresh",
    "mcp/toggle",
    "mcp_catalog/add",
    "mcp_catalog/login",
    "mcp_catalog/logout",
    "mcp_catalog/read",
    "mcp_catalog/refresh",
    "mcp_catalog/remove",
    "mcp_catalog/toggle",
    "narration/summarize",
    "plugin/info",
    "plugin/reload",
    "plugin_catalog/read",
    "plugins/read",
    "projectLinks/create",
    "projectLinks/inspectRoot",
    "projectLinks/link",
    "projectLinks/list",
    "projectLinks/picker/load",
    "projectLinks/picker/loadMore",
    "projectLinks/resolveRoot",
    "projectLinks/save",
    "projectLinks/unlink",
    "providerAuth/read",
    "review/approve",
    "review/baseline",
    "review/hunks",
    "review/revert",
    "review/state",
    "review/turnDiff",
    "runtime/read",
    "session/agent/update",
    "session/compact",
    "session/context/inject",
    "session/continue",
    "session/delete",
    "session/fork",
    "session/history/clear",
    "session/history/get",
    "session/history/list",
    "session/list",
    "session/log/read",
    "session/pin",
    "session/read",
    "session/ready/read",
    "session/ready/wait",
    "session/relocate",
    "session/rename",
    "session/resume",
    "session/rewind",
    "session/rewind/read",
    "session/settings/update",
    "session/shellCommand",
    "session/start",
    "session/stop",
    "session/title/update",
    "session/turn/enqueue",
    "session/turn/queue/read",
    "session/turn/queue/remove",
    "session/turn/queue/replace",
    "session/turn/queue/resume",
    "session/turn/queue/steer",
    "session/turns/list",
    "shell/interrupt",
    "shell/run",
    "skills/catalog",
    "skills/convertLocal",
    "skills/detail",
    "skills/import",
    "skills/installed",
    "skills/list",
    "skills/remove",
    "skills/setAlias",
    "skills/setEnabled",
    "skills/setLatest",
    "skills/setVersion",
    "skills/updates",
    "skills/versions",
    "stats/read",
    "telemetry/record",
    "tools/list",
    "turn/interrupt",
    "turn/start",
    "turn/steer",
    "vibeCode/projects/cancel",
    "vibeCode/projects/create",
    "vibeCode/projects/loadMore",
    "vibeCode/projects/open",
    "vibeCode/projects/recover",
    "vibeCode/projects/select",
    "vibeCode/projects/unlink",
    "vibeCode/teleport/cancel",
    "vibeCode/teleport/push/respond",
    "vibeCode/teleport/start",
    "workspace/git/checkouts",
    "workspace/git/worktrees/limit/update",
    "workspace/git/worktrees/list",
    "workspace/git/worktrees/prune",
    "workspace/git/worktrees/remove",
    "workspace/prompt/prepare",
    "workspace/trust/decision",
    "workspace/trust/status",
    "workspace/trust/untrustedConfig",
];

/// Reports whether `method` is part of the negotiated surface.
#[must_use]
pub fn is_server_method(method: &str) -> bool {
    SERVER_METHODS.binary_search(&method).is_ok()
}

#[cfg(test)]
mod methods_tests;
